version: "3"

services:
  db:
    image: postgres
    container_name: db_ignite
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - ./pgdata:/data/postgres
    #network_mode: host #obsoleto
  app:
    build: .
    container_name: rentalx
    links:
      - db
    depends_on:
      - db
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    #network_mode: host #obsoleto
